name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: gaelreyrol

      - name: Run Dhall linter
        run: nix develop --command dhall lint Resume/*.dhall

      - name: Run Formatter check
        run: nix fmt . -- --check

      - name: Run Flake check
        run: nix flake check